# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: system.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csystem.proto\"\x0f\n\rSystemRequest\"J\n\tConfigDto\x12\x15\n\x05\x65mail\x18\x01 \x01(\x0b\x32\x06.Email\x12\x13\n\x04yapi\x18\x02 \x01(\x0b\x32\x05.Yapi\x12\x11\n\x03oss\x18\x03 \x01(\x0b\x32\x04.Oss\"E\n\x0eSystemResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x18\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\n.ConfigDto\"C\n\x05\x45mail\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0c\n\x04host\x18\x03 \x01(\t\x12\n\n\x02to\x18\x04 \x01(\t\"\x15\n\x04Yapi\x12\r\n\x05token\x18\x01 \x01(\t\"}\n\x03Oss\x12\x10\n\x08oss_type\x18\x01 \x01(\t\x12\x15\n\raccess_key_id\x18\x02 \x01(\t\x12\x19\n\x11\x61\x63\x63\x65ss_key_secret\x18\x03 \x01(\t\x12\x0e\n\x06\x62ucket\x18\x04 \x01(\t\x12\x15\n\x08\x65ndpoint\x18\x05 \x01(\tH\x00\x88\x01\x01\x42\x0b\n\t_endpoint\"f\n\x08\x45mailDto\x12\x0f\n\x07subject\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x10\n\x08receiver\x18\x03 \x03(\t\x12\x17\n\nattachment\x18\x04 \x01(\tH\x00\x88\x01\x01\x42\r\n\x0b_attachment2\x9e\x01\n\x06system\x12\x34\n\x0fgetSystemConfig\x12\x0e.SystemRequest\x1a\x0f.SystemResponse\"\x00\x12\x33\n\x12updateSystemConfig\x12\n.ConfigDto\x1a\x0f.SystemResponse\"\x00\x12)\n\tsendEmail\x12\t.EmailDto\x1a\x0f.SystemResponse\"\x00\x62\x06proto3')



_SYSTEMREQUEST = DESCRIPTOR.message_types_by_name['SystemRequest']
_CONFIGDTO = DESCRIPTOR.message_types_by_name['ConfigDto']
_SYSTEMRESPONSE = DESCRIPTOR.message_types_by_name['SystemResponse']
_EMAIL = DESCRIPTOR.message_types_by_name['Email']
_YAPI = DESCRIPTOR.message_types_by_name['Yapi']
_OSS = DESCRIPTOR.message_types_by_name['Oss']
_EMAILDTO = DESCRIPTOR.message_types_by_name['EmailDto']
SystemRequest = _reflection.GeneratedProtocolMessageType('SystemRequest', (_message.Message,), {
  'DESCRIPTOR' : _SYSTEMREQUEST,
  '__module__' : 'system_pb2'
  # @@protoc_insertion_point(class_scope:SystemRequest)
  })
_sym_db.RegisterMessage(SystemRequest)

ConfigDto = _reflection.GeneratedProtocolMessageType('ConfigDto', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGDTO,
  '__module__' : 'system_pb2'
  # @@protoc_insertion_point(class_scope:ConfigDto)
  })
_sym_db.RegisterMessage(ConfigDto)

SystemResponse = _reflection.GeneratedProtocolMessageType('SystemResponse', (_message.Message,), {
  'DESCRIPTOR' : _SYSTEMRESPONSE,
  '__module__' : 'system_pb2'
  # @@protoc_insertion_point(class_scope:SystemResponse)
  })
_sym_db.RegisterMessage(SystemResponse)

Email = _reflection.GeneratedProtocolMessageType('Email', (_message.Message,), {
  'DESCRIPTOR' : _EMAIL,
  '__module__' : 'system_pb2'
  # @@protoc_insertion_point(class_scope:Email)
  })
_sym_db.RegisterMessage(Email)

Yapi = _reflection.GeneratedProtocolMessageType('Yapi', (_message.Message,), {
  'DESCRIPTOR' : _YAPI,
  '__module__' : 'system_pb2'
  # @@protoc_insertion_point(class_scope:Yapi)
  })
_sym_db.RegisterMessage(Yapi)

Oss = _reflection.GeneratedProtocolMessageType('Oss', (_message.Message,), {
  'DESCRIPTOR' : _OSS,
  '__module__' : 'system_pb2'
  # @@protoc_insertion_point(class_scope:Oss)
  })
_sym_db.RegisterMessage(Oss)

EmailDto = _reflection.GeneratedProtocolMessageType('EmailDto', (_message.Message,), {
  'DESCRIPTOR' : _EMAILDTO,
  '__module__' : 'system_pb2'
  # @@protoc_insertion_point(class_scope:EmailDto)
  })
_sym_db.RegisterMessage(EmailDto)

_SYSTEM = DESCRIPTOR.services_by_name['system']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SYSTEMREQUEST._serialized_start=16
  _SYSTEMREQUEST._serialized_end=31
  _CONFIGDTO._serialized_start=33
  _CONFIGDTO._serialized_end=107
  _SYSTEMRESPONSE._serialized_start=109
  _SYSTEMRESPONSE._serialized_end=178
  _EMAIL._serialized_start=180
  _EMAIL._serialized_end=247
  _YAPI._serialized_start=249
  _YAPI._serialized_end=270
  _OSS._serialized_start=272
  _OSS._serialized_end=397
  _EMAILDTO._serialized_start=399
  _EMAILDTO._serialized_end=501
  _SYSTEM._serialized_start=504
  _SYSTEM._serialized_end=662
# @@protoc_insertion_point(module_scope)
