# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proto.dashboard_pb2 as dashboard__pb2


class dashboardStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.statistics = channel.unary_unary(
                '/dashboard/statistics',
                request_serializer=dashboard__pb2.DashboardRequest.SerializeToString,
                response_deserializer=dashboard__pb2.StatisticsResponse.FromString,
                )
        self.workspace = channel.unary_unary(
                '/dashboard/workspace',
                request_serializer=dashboard__pb2.DashboardRequest.SerializeToString,
                response_deserializer=dashboard__pb2.WorkspaceResponse.FromString,
                )


class dashboardServicer(object):
    """Missing associated documentation comment in .proto file."""

    def statistics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def workspace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_dashboardServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'statistics': grpc.unary_unary_rpc_method_handler(
                    servicer.statistics,
                    request_deserializer=dashboard__pb2.DashboardRequest.FromString,
                    response_serializer=dashboard__pb2.StatisticsResponse.SerializeToString,
            ),
            'workspace': grpc.unary_unary_rpc_method_handler(
                    servicer.workspace,
                    request_deserializer=dashboard__pb2.DashboardRequest.FromString,
                    response_serializer=dashboard__pb2.WorkspaceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dashboard', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class dashboard(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def statistics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dashboard/statistics',
            dashboard__pb2.DashboardRequest.SerializeToString,
            dashboard__pb2.StatisticsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def workspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dashboard/workspace',
            dashboard__pb2.DashboardRequest.SerializeToString,
            dashboard__pb2.WorkspaceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
