# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proto.testcase_pb2 as testcase__pb2


class testcaseStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.listTestCase = channel.unary_unary(
                '/testcase/listTestCase',
                request_serializer=testcase__pb2.ListTestCaseDto.SerializeToString,
                response_deserializer=testcase__pb2.ListTestCaseResponse.FromString,
                )
        self.insertTestCase = channel.unary_unary(
                '/testcase/insertTestCase',
                request_serializer=testcase__pb2.TestCaseDto.SerializeToString,
                response_deserializer=testcase__pb2.InsertTestCaseResponseDto.FromString,
                )
        self.createTestCase = channel.unary_unary(
                '/testcase/createTestCase',
                request_serializer=testcase__pb2.TestCaseInfoDto.SerializeToString,
                response_deserializer=testcase__pb2.TestCaseResponse.FromString,
                )
        self.updateTestCase = channel.unary_unary(
                '/testcase/updateTestCase',
                request_serializer=testcase__pb2.TestCaseDto.SerializeToString,
                response_deserializer=testcase__pb2.UpdateTestCaseResponseDto.FromString,
                )
        self.deleteTestCase = channel.unary_unary(
                '/testcase/deleteTestCase',
                request_serializer=testcase__pb2.DeleteTestCaseDto.SerializeToString,
                response_deserializer=testcase__pb2.TestCaseResponse.FromString,
                )
        self.queryTestCase = channel.unary_unary(
                '/testcase/queryTestCase',
                request_serializer=testcase__pb2.QueryTestCaseDto.SerializeToString,
                response_deserializer=testcase__pb2.QueryTestCaseResponseDto.FromString,
                )
        self.moveTestCase = channel.unary_unary(
                '/testcase/moveTestCase',
                request_serializer=testcase__pb2.MoveTestCaseDto.SerializeToString,
                response_deserializer=testcase__pb2.TestCaseResponse.FromString,
                )
        self.insertAsserts = channel.unary_unary(
                '/testcase/insertAsserts',
                request_serializer=testcase__pb2.TestCaseAssertsDto.SerializeToString,
                response_deserializer=testcase__pb2.TestCaseAssertsResponseDto.FromString,
                )
        self.updateAsserts = channel.unary_unary(
                '/testcase/updateAsserts',
                request_serializer=testcase__pb2.TestCaseAssertsDto.SerializeToString,
                response_deserializer=testcase__pb2.TestCaseAssertsResponseDto.FromString,
                )
        self.deleteAsserts = channel.unary_unary(
                '/testcase/deleteAsserts',
                request_serializer=testcase__pb2.CustomDto.SerializeToString,
                response_deserializer=testcase__pb2.TestCaseResponse.FromString,
                )
        self.insertConstructor = channel.unary_unary(
                '/testcase/insertConstructor',
                request_serializer=testcase__pb2.ConstructorDto.SerializeToString,
                response_deserializer=testcase__pb2.TestCaseResponse.FromString,
                )
        self.updateConstructor = channel.unary_unary(
                '/testcase/updateConstructor',
                request_serializer=testcase__pb2.ConstructorDto.SerializeToString,
                response_deserializer=testcase__pb2.TestCaseResponse.FromString,
                )
        self.deleteConstructor = channel.unary_unary(
                '/testcase/deleteConstructor',
                request_serializer=testcase__pb2.CustomDto.SerializeToString,
                response_deserializer=testcase__pb2.TestCaseResponse.FromString,
                )
        self.reorderConstructor = channel.unary_unary(
                '/testcase/reorderConstructor',
                request_serializer=testcase__pb2.ListConstructorIndexDto.SerializeToString,
                response_deserializer=testcase__pb2.TestCaseResponse.FromString,
                )
        self.queryConstructorTree = channel.unary_unary(
                '/testcase/queryConstructorTree',
                request_serializer=testcase__pb2.QueryConstructorTreeDto.SerializeToString,
                response_deserializer=testcase__pb2.QueryConstructorTreeResponse.FromString,
                )
        self.queryConstructor = channel.unary_unary(
                '/testcase/queryConstructor',
                request_serializer=testcase__pb2.CustomDto.SerializeToString,
                response_deserializer=testcase__pb2.QueryConstructorResponse.FromString,
                )
        self.listConstructor = channel.unary_unary(
                '/testcase/listConstructor',
                request_serializer=testcase__pb2.ListConstructorDto.SerializeToString,
                response_deserializer=testcase__pb2.ListConstructorResponse.FromString,
                )
        self.queryTestReport = channel.unary_unary(
                '/testcase/queryTestReport',
                request_serializer=testcase__pb2.CustomDto.SerializeToString,
                response_deserializer=testcase__pb2.QueryReportResponse.FromString,
                )
        self.listTestReport = channel.unary_unary(
                '/testcase/listTestReport',
                request_serializer=testcase__pb2.ListReportDto.SerializeToString,
                response_deserializer=testcase__pb2.ListReportResponse.FromString,
                )
        self.queryXmindData = channel.unary_unary(
                '/testcase/queryXmindData',
                request_serializer=testcase__pb2.CustomDto.SerializeToString,
                response_deserializer=testcase__pb2.QueryXmindResponse.FromString,
                )
        self.queryTestCaseDirTree = channel.unary_unary(
                '/testcase/queryTestCaseDirTree',
                request_serializer=testcase__pb2.QueryTestCaseDirTree.SerializeToString,
                response_deserializer=testcase__pb2.QueryTestCaseDirTreeResponse.FromString,
                )
        self.queryTestCaseTree = channel.unary_unary(
                '/testcase/queryTestCaseTree',
                request_serializer=testcase__pb2.TestPlanCaseDto.SerializeToString,
                response_deserializer=testcase__pb2.TestPlanTreeResponse.FromString,
                )
        self.queryTestCaseDir = channel.unary_unary(
                '/testcase/queryTestCaseDir',
                request_serializer=testcase__pb2.QueryTestCaseDir.SerializeToString,
                response_deserializer=testcase__pb2.QueryTestCaseDirectoryResponseDto.FromString,
                )
        self.insertTestCaseDir = channel.unary_unary(
                '/testcase/insertTestCaseDir',
                request_serializer=testcase__pb2.TestCaseDirDto.SerializeToString,
                response_deserializer=testcase__pb2.TestCaseResponse.FromString,
                )
        self.updateTestCaseDir = channel.unary_unary(
                '/testcase/updateTestCaseDir',
                request_serializer=testcase__pb2.TestCaseDirDto.SerializeToString,
                response_deserializer=testcase__pb2.TestCaseResponse.FromString,
                )
        self.deleteTestCaseDir = channel.unary_unary(
                '/testcase/deleteTestCaseDir',
                request_serializer=testcase__pb2.CustomDto.SerializeToString,
                response_deserializer=testcase__pb2.TestCaseResponse.FromString,
                )
        self.insertTestData = channel.unary_unary(
                '/testcase/insertTestData',
                request_serializer=testcase__pb2.TestCaseDataDto.SerializeToString,
                response_deserializer=testcase__pb2.TestCaseDataResponse.FromString,
                )
        self.updateTestData = channel.unary_unary(
                '/testcase/updateTestData',
                request_serializer=testcase__pb2.TestCaseDataDto.SerializeToString,
                response_deserializer=testcase__pb2.TestCaseDataResponse.FromString,
                )
        self.deleteTestData = channel.unary_unary(
                '/testcase/deleteTestData',
                request_serializer=testcase__pb2.CustomDto.SerializeToString,
                response_deserializer=testcase__pb2.TestCaseResponse.FromString,
                )
        self.insertParams = channel.unary_unary(
                '/testcase/insertParams',
                request_serializer=testcase__pb2.TestCaseOutParametersDto.SerializeToString,
                response_deserializer=testcase__pb2.TestCaseOutParametersResponse.FromString,
                )
        self.updateParams = channel.unary_unary(
                '/testcase/updateParams',
                request_serializer=testcase__pb2.TestCaseOutParametersDto.SerializeToString,
                response_deserializer=testcase__pb2.TestCaseOutParametersResponse.FromString,
                )
        self.batchUpdateParams = channel.unary_unary(
                '/testcase/batchUpdateParams',
                request_serializer=testcase__pb2.BatchUpdateOutParametersDto.SerializeToString,
                response_deserializer=testcase__pb2.BatchUpdateOutParametersResponse.FromString,
                )
        self.deleteParams = channel.unary_unary(
                '/testcase/deleteParams',
                request_serializer=testcase__pb2.CustomDto.SerializeToString,
                response_deserializer=testcase__pb2.TestCaseResponse.FromString,
                )
        self.startRecord = channel.unary_unary(
                '/testcase/startRecord',
                request_serializer=testcase__pb2.TestCaseRequest.SerializeToString,
                response_deserializer=testcase__pb2.TestCaseResponse.FromString,
                )
        self.stopRecord = channel.unary_unary(
                '/testcase/stopRecord',
                request_serializer=testcase__pb2.TestCaseRequest.SerializeToString,
                response_deserializer=testcase__pb2.TestCaseResponse.FromString,
                )
        self.removeRecord = channel.unary_unary(
                '/testcase/removeRecord',
                request_serializer=testcase__pb2.TestCaseRequest.SerializeToString,
                response_deserializer=testcase__pb2.TestCaseResponse.FromString,
                )
        self.queryRecordStatus = channel.unary_unary(
                '/testcase/queryRecordStatus',
                request_serializer=testcase__pb2.TestCaseRequest.SerializeToString,
                response_deserializer=testcase__pb2.TestCaseResponse.FromString,
                )
        self.generateTestCase = channel.unary_unary(
                '/testcase/generateTestCase',
                request_serializer=testcase__pb2.TestCaseGeneratorDto.SerializeToString,
                response_deserializer=testcase__pb2.TestCaseGenerateResponse.FromString,
                )
        self.importTestCase = channel.unary_unary(
                '/testcase/importTestCase',
                request_serializer=testcase__pb2.ImportCaseDto.SerializeToString,
                response_deserializer=testcase__pb2.ImportTestCaseResponse.FromString,
                )
        self.listTestPlan = channel.unary_unary(
                '/testcase/listTestPlan',
                request_serializer=testcase__pb2.ListTestPlanDto.SerializeToString,
                response_deserializer=testcase__pb2.ListTestPlanResponse.FromString,
                )
        self.insertTestPlan = channel.unary_unary(
                '/testcase/insertTestPlan',
                request_serializer=testcase__pb2.TestPlanDto.SerializeToString,
                response_deserializer=testcase__pb2.TestCaseResponse.FromString,
                )
        self.updateTestPlan = channel.unary_unary(
                '/testcase/updateTestPlan',
                request_serializer=testcase__pb2.TestPlanDto.SerializeToString,
                response_deserializer=testcase__pb2.TestCaseResponse.FromString,
                )
        self.deleteTestPlan = channel.unary_unary(
                '/testcase/deleteTestPlan',
                request_serializer=testcase__pb2.CustomDto.SerializeToString,
                response_deserializer=testcase__pb2.TestCaseResponse.FromString,
                )
        self.switchTestPlan = channel.unary_unary(
                '/testcase/switchTestPlan',
                request_serializer=testcase__pb2.SwitchTestPlanDto.SerializeToString,
                response_deserializer=testcase__pb2.TestCaseResponse.FromString,
                )
        self.executeTestPlan = channel.unary_unary(
                '/testcase/executeTestPlan',
                request_serializer=testcase__pb2.CustomDto.SerializeToString,
                response_deserializer=testcase__pb2.TestCaseResponse.FromString,
                )
        self.followTestPlan = channel.unary_unary(
                '/testcase/followTestPlan',
                request_serializer=testcase__pb2.CustomDto.SerializeToString,
                response_deserializer=testcase__pb2.TestCaseResponse.FromString,
                )
        self.unFollowTestPlan = channel.unary_unary(
                '/testcase/unFollowTestPlan',
                request_serializer=testcase__pb2.CustomDto.SerializeToString,
                response_deserializer=testcase__pb2.TestCaseResponse.FromString,
                )
        self.queryUserFollowTestPlan = channel.unary_unary(
                '/testcase/queryUserFollowTestPlan',
                request_serializer=testcase__pb2.TestCaseRequest.SerializeToString,
                response_deserializer=testcase__pb2.QueryFollowPlanResponse.FromString,
                )


class testcaseServicer(object):
    """Missing associated documentation comment in .proto file."""

    def listTestCase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def insertTestCase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createTestCase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateTestCase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteTestCase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def queryTestCase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def moveTestCase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def insertAsserts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateAsserts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteAsserts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def insertConstructor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateConstructor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteConstructor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def reorderConstructor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def queryConstructorTree(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def queryConstructor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listConstructor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def queryTestReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listTestReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def queryXmindData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def queryTestCaseDirTree(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def queryTestCaseTree(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def queryTestCaseDir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def insertTestCaseDir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateTestCaseDir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteTestCaseDir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def insertTestData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateTestData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteTestData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def insertParams(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateParams(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def batchUpdateParams(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteParams(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def startRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def stopRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def removeRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def queryRecordStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def generateTestCase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def importTestCase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listTestPlan(self, request, context):
        """测试计划
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def insertTestPlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateTestPlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteTestPlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def switchTestPlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def executeTestPlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def followTestPlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def unFollowTestPlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def queryUserFollowTestPlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_testcaseServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'listTestCase': grpc.unary_unary_rpc_method_handler(
                    servicer.listTestCase,
                    request_deserializer=testcase__pb2.ListTestCaseDto.FromString,
                    response_serializer=testcase__pb2.ListTestCaseResponse.SerializeToString,
            ),
            'insertTestCase': grpc.unary_unary_rpc_method_handler(
                    servicer.insertTestCase,
                    request_deserializer=testcase__pb2.TestCaseDto.FromString,
                    response_serializer=testcase__pb2.InsertTestCaseResponseDto.SerializeToString,
            ),
            'createTestCase': grpc.unary_unary_rpc_method_handler(
                    servicer.createTestCase,
                    request_deserializer=testcase__pb2.TestCaseInfoDto.FromString,
                    response_serializer=testcase__pb2.TestCaseResponse.SerializeToString,
            ),
            'updateTestCase': grpc.unary_unary_rpc_method_handler(
                    servicer.updateTestCase,
                    request_deserializer=testcase__pb2.TestCaseDto.FromString,
                    response_serializer=testcase__pb2.UpdateTestCaseResponseDto.SerializeToString,
            ),
            'deleteTestCase': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteTestCase,
                    request_deserializer=testcase__pb2.DeleteTestCaseDto.FromString,
                    response_serializer=testcase__pb2.TestCaseResponse.SerializeToString,
            ),
            'queryTestCase': grpc.unary_unary_rpc_method_handler(
                    servicer.queryTestCase,
                    request_deserializer=testcase__pb2.QueryTestCaseDto.FromString,
                    response_serializer=testcase__pb2.QueryTestCaseResponseDto.SerializeToString,
            ),
            'moveTestCase': grpc.unary_unary_rpc_method_handler(
                    servicer.moveTestCase,
                    request_deserializer=testcase__pb2.MoveTestCaseDto.FromString,
                    response_serializer=testcase__pb2.TestCaseResponse.SerializeToString,
            ),
            'insertAsserts': grpc.unary_unary_rpc_method_handler(
                    servicer.insertAsserts,
                    request_deserializer=testcase__pb2.TestCaseAssertsDto.FromString,
                    response_serializer=testcase__pb2.TestCaseAssertsResponseDto.SerializeToString,
            ),
            'updateAsserts': grpc.unary_unary_rpc_method_handler(
                    servicer.updateAsserts,
                    request_deserializer=testcase__pb2.TestCaseAssertsDto.FromString,
                    response_serializer=testcase__pb2.TestCaseAssertsResponseDto.SerializeToString,
            ),
            'deleteAsserts': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteAsserts,
                    request_deserializer=testcase__pb2.CustomDto.FromString,
                    response_serializer=testcase__pb2.TestCaseResponse.SerializeToString,
            ),
            'insertConstructor': grpc.unary_unary_rpc_method_handler(
                    servicer.insertConstructor,
                    request_deserializer=testcase__pb2.ConstructorDto.FromString,
                    response_serializer=testcase__pb2.TestCaseResponse.SerializeToString,
            ),
            'updateConstructor': grpc.unary_unary_rpc_method_handler(
                    servicer.updateConstructor,
                    request_deserializer=testcase__pb2.ConstructorDto.FromString,
                    response_serializer=testcase__pb2.TestCaseResponse.SerializeToString,
            ),
            'deleteConstructor': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteConstructor,
                    request_deserializer=testcase__pb2.CustomDto.FromString,
                    response_serializer=testcase__pb2.TestCaseResponse.SerializeToString,
            ),
            'reorderConstructor': grpc.unary_unary_rpc_method_handler(
                    servicer.reorderConstructor,
                    request_deserializer=testcase__pb2.ListConstructorIndexDto.FromString,
                    response_serializer=testcase__pb2.TestCaseResponse.SerializeToString,
            ),
            'queryConstructorTree': grpc.unary_unary_rpc_method_handler(
                    servicer.queryConstructorTree,
                    request_deserializer=testcase__pb2.QueryConstructorTreeDto.FromString,
                    response_serializer=testcase__pb2.QueryConstructorTreeResponse.SerializeToString,
            ),
            'queryConstructor': grpc.unary_unary_rpc_method_handler(
                    servicer.queryConstructor,
                    request_deserializer=testcase__pb2.CustomDto.FromString,
                    response_serializer=testcase__pb2.QueryConstructorResponse.SerializeToString,
            ),
            'listConstructor': grpc.unary_unary_rpc_method_handler(
                    servicer.listConstructor,
                    request_deserializer=testcase__pb2.ListConstructorDto.FromString,
                    response_serializer=testcase__pb2.ListConstructorResponse.SerializeToString,
            ),
            'queryTestReport': grpc.unary_unary_rpc_method_handler(
                    servicer.queryTestReport,
                    request_deserializer=testcase__pb2.CustomDto.FromString,
                    response_serializer=testcase__pb2.QueryReportResponse.SerializeToString,
            ),
            'listTestReport': grpc.unary_unary_rpc_method_handler(
                    servicer.listTestReport,
                    request_deserializer=testcase__pb2.ListReportDto.FromString,
                    response_serializer=testcase__pb2.ListReportResponse.SerializeToString,
            ),
            'queryXmindData': grpc.unary_unary_rpc_method_handler(
                    servicer.queryXmindData,
                    request_deserializer=testcase__pb2.CustomDto.FromString,
                    response_serializer=testcase__pb2.QueryXmindResponse.SerializeToString,
            ),
            'queryTestCaseDirTree': grpc.unary_unary_rpc_method_handler(
                    servicer.queryTestCaseDirTree,
                    request_deserializer=testcase__pb2.QueryTestCaseDirTree.FromString,
                    response_serializer=testcase__pb2.QueryTestCaseDirTreeResponse.SerializeToString,
            ),
            'queryTestCaseTree': grpc.unary_unary_rpc_method_handler(
                    servicer.queryTestCaseTree,
                    request_deserializer=testcase__pb2.TestPlanCaseDto.FromString,
                    response_serializer=testcase__pb2.TestPlanTreeResponse.SerializeToString,
            ),
            'queryTestCaseDir': grpc.unary_unary_rpc_method_handler(
                    servicer.queryTestCaseDir,
                    request_deserializer=testcase__pb2.QueryTestCaseDir.FromString,
                    response_serializer=testcase__pb2.QueryTestCaseDirectoryResponseDto.SerializeToString,
            ),
            'insertTestCaseDir': grpc.unary_unary_rpc_method_handler(
                    servicer.insertTestCaseDir,
                    request_deserializer=testcase__pb2.TestCaseDirDto.FromString,
                    response_serializer=testcase__pb2.TestCaseResponse.SerializeToString,
            ),
            'updateTestCaseDir': grpc.unary_unary_rpc_method_handler(
                    servicer.updateTestCaseDir,
                    request_deserializer=testcase__pb2.TestCaseDirDto.FromString,
                    response_serializer=testcase__pb2.TestCaseResponse.SerializeToString,
            ),
            'deleteTestCaseDir': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteTestCaseDir,
                    request_deserializer=testcase__pb2.CustomDto.FromString,
                    response_serializer=testcase__pb2.TestCaseResponse.SerializeToString,
            ),
            'insertTestData': grpc.unary_unary_rpc_method_handler(
                    servicer.insertTestData,
                    request_deserializer=testcase__pb2.TestCaseDataDto.FromString,
                    response_serializer=testcase__pb2.TestCaseDataResponse.SerializeToString,
            ),
            'updateTestData': grpc.unary_unary_rpc_method_handler(
                    servicer.updateTestData,
                    request_deserializer=testcase__pb2.TestCaseDataDto.FromString,
                    response_serializer=testcase__pb2.TestCaseDataResponse.SerializeToString,
            ),
            'deleteTestData': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteTestData,
                    request_deserializer=testcase__pb2.CustomDto.FromString,
                    response_serializer=testcase__pb2.TestCaseResponse.SerializeToString,
            ),
            'insertParams': grpc.unary_unary_rpc_method_handler(
                    servicer.insertParams,
                    request_deserializer=testcase__pb2.TestCaseOutParametersDto.FromString,
                    response_serializer=testcase__pb2.TestCaseOutParametersResponse.SerializeToString,
            ),
            'updateParams': grpc.unary_unary_rpc_method_handler(
                    servicer.updateParams,
                    request_deserializer=testcase__pb2.TestCaseOutParametersDto.FromString,
                    response_serializer=testcase__pb2.TestCaseOutParametersResponse.SerializeToString,
            ),
            'batchUpdateParams': grpc.unary_unary_rpc_method_handler(
                    servicer.batchUpdateParams,
                    request_deserializer=testcase__pb2.BatchUpdateOutParametersDto.FromString,
                    response_serializer=testcase__pb2.BatchUpdateOutParametersResponse.SerializeToString,
            ),
            'deleteParams': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteParams,
                    request_deserializer=testcase__pb2.CustomDto.FromString,
                    response_serializer=testcase__pb2.TestCaseResponse.SerializeToString,
            ),
            'startRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.startRecord,
                    request_deserializer=testcase__pb2.TestCaseRequest.FromString,
                    response_serializer=testcase__pb2.TestCaseResponse.SerializeToString,
            ),
            'stopRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.stopRecord,
                    request_deserializer=testcase__pb2.TestCaseRequest.FromString,
                    response_serializer=testcase__pb2.TestCaseResponse.SerializeToString,
            ),
            'removeRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.removeRecord,
                    request_deserializer=testcase__pb2.TestCaseRequest.FromString,
                    response_serializer=testcase__pb2.TestCaseResponse.SerializeToString,
            ),
            'queryRecordStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.queryRecordStatus,
                    request_deserializer=testcase__pb2.TestCaseRequest.FromString,
                    response_serializer=testcase__pb2.TestCaseResponse.SerializeToString,
            ),
            'generateTestCase': grpc.unary_unary_rpc_method_handler(
                    servicer.generateTestCase,
                    request_deserializer=testcase__pb2.TestCaseGeneratorDto.FromString,
                    response_serializer=testcase__pb2.TestCaseGenerateResponse.SerializeToString,
            ),
            'importTestCase': grpc.unary_unary_rpc_method_handler(
                    servicer.importTestCase,
                    request_deserializer=testcase__pb2.ImportCaseDto.FromString,
                    response_serializer=testcase__pb2.ImportTestCaseResponse.SerializeToString,
            ),
            'listTestPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.listTestPlan,
                    request_deserializer=testcase__pb2.ListTestPlanDto.FromString,
                    response_serializer=testcase__pb2.ListTestPlanResponse.SerializeToString,
            ),
            'insertTestPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.insertTestPlan,
                    request_deserializer=testcase__pb2.TestPlanDto.FromString,
                    response_serializer=testcase__pb2.TestCaseResponse.SerializeToString,
            ),
            'updateTestPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.updateTestPlan,
                    request_deserializer=testcase__pb2.TestPlanDto.FromString,
                    response_serializer=testcase__pb2.TestCaseResponse.SerializeToString,
            ),
            'deleteTestPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteTestPlan,
                    request_deserializer=testcase__pb2.CustomDto.FromString,
                    response_serializer=testcase__pb2.TestCaseResponse.SerializeToString,
            ),
            'switchTestPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.switchTestPlan,
                    request_deserializer=testcase__pb2.SwitchTestPlanDto.FromString,
                    response_serializer=testcase__pb2.TestCaseResponse.SerializeToString,
            ),
            'executeTestPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.executeTestPlan,
                    request_deserializer=testcase__pb2.CustomDto.FromString,
                    response_serializer=testcase__pb2.TestCaseResponse.SerializeToString,
            ),
            'followTestPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.followTestPlan,
                    request_deserializer=testcase__pb2.CustomDto.FromString,
                    response_serializer=testcase__pb2.TestCaseResponse.SerializeToString,
            ),
            'unFollowTestPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.unFollowTestPlan,
                    request_deserializer=testcase__pb2.CustomDto.FromString,
                    response_serializer=testcase__pb2.TestCaseResponse.SerializeToString,
            ),
            'queryUserFollowTestPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.queryUserFollowTestPlan,
                    request_deserializer=testcase__pb2.TestCaseRequest.FromString,
                    response_serializer=testcase__pb2.QueryFollowPlanResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'testcase', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class testcase(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def listTestCase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testcase/listTestCase',
            testcase__pb2.ListTestCaseDto.SerializeToString,
            testcase__pb2.ListTestCaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def insertTestCase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testcase/insertTestCase',
            testcase__pb2.TestCaseDto.SerializeToString,
            testcase__pb2.InsertTestCaseResponseDto.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def createTestCase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testcase/createTestCase',
            testcase__pb2.TestCaseInfoDto.SerializeToString,
            testcase__pb2.TestCaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def updateTestCase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testcase/updateTestCase',
            testcase__pb2.TestCaseDto.SerializeToString,
            testcase__pb2.UpdateTestCaseResponseDto.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def deleteTestCase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testcase/deleteTestCase',
            testcase__pb2.DeleteTestCaseDto.SerializeToString,
            testcase__pb2.TestCaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def queryTestCase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testcase/queryTestCase',
            testcase__pb2.QueryTestCaseDto.SerializeToString,
            testcase__pb2.QueryTestCaseResponseDto.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def moveTestCase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testcase/moveTestCase',
            testcase__pb2.MoveTestCaseDto.SerializeToString,
            testcase__pb2.TestCaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def insertAsserts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testcase/insertAsserts',
            testcase__pb2.TestCaseAssertsDto.SerializeToString,
            testcase__pb2.TestCaseAssertsResponseDto.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def updateAsserts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testcase/updateAsserts',
            testcase__pb2.TestCaseAssertsDto.SerializeToString,
            testcase__pb2.TestCaseAssertsResponseDto.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def deleteAsserts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testcase/deleteAsserts',
            testcase__pb2.CustomDto.SerializeToString,
            testcase__pb2.TestCaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def insertConstructor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testcase/insertConstructor',
            testcase__pb2.ConstructorDto.SerializeToString,
            testcase__pb2.TestCaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def updateConstructor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testcase/updateConstructor',
            testcase__pb2.ConstructorDto.SerializeToString,
            testcase__pb2.TestCaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def deleteConstructor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testcase/deleteConstructor',
            testcase__pb2.CustomDto.SerializeToString,
            testcase__pb2.TestCaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def reorderConstructor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testcase/reorderConstructor',
            testcase__pb2.ListConstructorIndexDto.SerializeToString,
            testcase__pb2.TestCaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def queryConstructorTree(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testcase/queryConstructorTree',
            testcase__pb2.QueryConstructorTreeDto.SerializeToString,
            testcase__pb2.QueryConstructorTreeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def queryConstructor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testcase/queryConstructor',
            testcase__pb2.CustomDto.SerializeToString,
            testcase__pb2.QueryConstructorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def listConstructor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testcase/listConstructor',
            testcase__pb2.ListConstructorDto.SerializeToString,
            testcase__pb2.ListConstructorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def queryTestReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testcase/queryTestReport',
            testcase__pb2.CustomDto.SerializeToString,
            testcase__pb2.QueryReportResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def listTestReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testcase/listTestReport',
            testcase__pb2.ListReportDto.SerializeToString,
            testcase__pb2.ListReportResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def queryXmindData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testcase/queryXmindData',
            testcase__pb2.CustomDto.SerializeToString,
            testcase__pb2.QueryXmindResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def queryTestCaseDirTree(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testcase/queryTestCaseDirTree',
            testcase__pb2.QueryTestCaseDirTree.SerializeToString,
            testcase__pb2.QueryTestCaseDirTreeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def queryTestCaseTree(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testcase/queryTestCaseTree',
            testcase__pb2.TestPlanCaseDto.SerializeToString,
            testcase__pb2.TestPlanTreeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def queryTestCaseDir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testcase/queryTestCaseDir',
            testcase__pb2.QueryTestCaseDir.SerializeToString,
            testcase__pb2.QueryTestCaseDirectoryResponseDto.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def insertTestCaseDir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testcase/insertTestCaseDir',
            testcase__pb2.TestCaseDirDto.SerializeToString,
            testcase__pb2.TestCaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def updateTestCaseDir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testcase/updateTestCaseDir',
            testcase__pb2.TestCaseDirDto.SerializeToString,
            testcase__pb2.TestCaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def deleteTestCaseDir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testcase/deleteTestCaseDir',
            testcase__pb2.CustomDto.SerializeToString,
            testcase__pb2.TestCaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def insertTestData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testcase/insertTestData',
            testcase__pb2.TestCaseDataDto.SerializeToString,
            testcase__pb2.TestCaseDataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def updateTestData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testcase/updateTestData',
            testcase__pb2.TestCaseDataDto.SerializeToString,
            testcase__pb2.TestCaseDataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def deleteTestData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testcase/deleteTestData',
            testcase__pb2.CustomDto.SerializeToString,
            testcase__pb2.TestCaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def insertParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testcase/insertParams',
            testcase__pb2.TestCaseOutParametersDto.SerializeToString,
            testcase__pb2.TestCaseOutParametersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def updateParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testcase/updateParams',
            testcase__pb2.TestCaseOutParametersDto.SerializeToString,
            testcase__pb2.TestCaseOutParametersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def batchUpdateParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testcase/batchUpdateParams',
            testcase__pb2.BatchUpdateOutParametersDto.SerializeToString,
            testcase__pb2.BatchUpdateOutParametersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def deleteParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testcase/deleteParams',
            testcase__pb2.CustomDto.SerializeToString,
            testcase__pb2.TestCaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def startRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testcase/startRecord',
            testcase__pb2.TestCaseRequest.SerializeToString,
            testcase__pb2.TestCaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def stopRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testcase/stopRecord',
            testcase__pb2.TestCaseRequest.SerializeToString,
            testcase__pb2.TestCaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def removeRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testcase/removeRecord',
            testcase__pb2.TestCaseRequest.SerializeToString,
            testcase__pb2.TestCaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def queryRecordStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testcase/queryRecordStatus',
            testcase__pb2.TestCaseRequest.SerializeToString,
            testcase__pb2.TestCaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def generateTestCase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testcase/generateTestCase',
            testcase__pb2.TestCaseGeneratorDto.SerializeToString,
            testcase__pb2.TestCaseGenerateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def importTestCase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testcase/importTestCase',
            testcase__pb2.ImportCaseDto.SerializeToString,
            testcase__pb2.ImportTestCaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def listTestPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testcase/listTestPlan',
            testcase__pb2.ListTestPlanDto.SerializeToString,
            testcase__pb2.ListTestPlanResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def insertTestPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testcase/insertTestPlan',
            testcase__pb2.TestPlanDto.SerializeToString,
            testcase__pb2.TestCaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def updateTestPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testcase/updateTestPlan',
            testcase__pb2.TestPlanDto.SerializeToString,
            testcase__pb2.TestCaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def deleteTestPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testcase/deleteTestPlan',
            testcase__pb2.CustomDto.SerializeToString,
            testcase__pb2.TestCaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def switchTestPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testcase/switchTestPlan',
            testcase__pb2.SwitchTestPlanDto.SerializeToString,
            testcase__pb2.TestCaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def executeTestPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testcase/executeTestPlan',
            testcase__pb2.CustomDto.SerializeToString,
            testcase__pb2.TestCaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def followTestPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testcase/followTestPlan',
            testcase__pb2.CustomDto.SerializeToString,
            testcase__pb2.TestCaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def unFollowTestPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testcase/unFollowTestPlan',
            testcase__pb2.CustomDto.SerializeToString,
            testcase__pb2.TestCaseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def queryUserFollowTestPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testcase/queryUserFollowTestPlan',
            testcase__pb2.TestCaseRequest.SerializeToString,
            testcase__pb2.QueryFollowPlanResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
